# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform LimeSurvey installation tasks
  when: limesurvey_enabled | bool
  tags:
    - setup-all
    - setup-limesurvey
    - install-all
    - install-limesurvey
  block:
    - name: Validate LimeSurvey configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install LimeSurvey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform LimeSurvey uninstallation tasks
  when: not limesurvey_enabled | bool
  tags:
    - setup-all
    - setup-limesurvey
  block:
    - name: Uninstall LimeSurvey
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
